# Generated by Django 4.1.5 on 2023-01-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=30, verbose_name="Program Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("st_id", models.SmallIntegerField(verbose_name="Student ID")),
                (
                    "st_name",
                    models.CharField(max_length=20, verbose_name="Student Name"),
                ),
                (
                    "st_dist",
                    models.CharField(max_length=20, verbose_name="Student Name"),
                ),
                ("st_dob", models.DateField(max_length=20, verbose_name="Birth Date")),
                ("st_edate", models.DateField(verbose_name="Enroll Date")),
                ("st_gpa", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "st_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentapp.program",
                        verbose_name="Program Name",
                    ),
                ),
            ],
        ),
    ]
