# Generated by Django 4.1.5 on 2023-01-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crs_id", models.PositiveSmallIntegerField(verbose_name="Course ID")),
                (
                    "crs_name",
                    models.CharField(max_length=20, verbose_name="Course Name"),
                ),
                (
                    "crs_credit",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="Course Credit"
                    ),
                ),
                (
                    "crs_at_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        verbose_name="Attendence Full Marks",
                    ),
                ),
                (
                    "crs_ct_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        max_digits=5,
                        verbose_name="CT Full Marks",
                    ),
                ),
                (
                    "crs_mid_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="MID Full Marks",
                    ),
                ),
                (
                    "crs_final_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=150,
                        max_digits=5,
                        verbose_name="Final Full Marks",
                    ),
                ),
            ],
        ),
    ]
